// generate-course — builds a founder's personalized course when they APPROVE
// their Founder Casefile. This is the successor to the retired generate-playbook,
// but it writes to the LIVE mission spine (missions / mission_steps) instead of
// the retired playbook_lessons — no parallel tracker.
//
//   module      = mission        (one per stage, owned by a mentor)
//   module step = mission_step    (a concrete, do-this-now action)
//
// The course is GENERATED BY AI from the founder's actual approved business —
// not stitched from pre-built template tracks. Claude reads the casefile + the
// Business Context Graph and returns an ordered, stage-by-stage program of
// concrete steps tailored to THIS business (an e-commerce founder gets "buy a
// domain → open your store → connect the domain → source your first product";
// a consultant gets a different path entirely). Steps that map to a real Bylda
// tool deep-link into it; the rest are plain, self-contained actions.
//
// If the AI call fails we fall back to the shared template curriculum
// (_shared/curriculum.ts) so a founder is never left without a course.
//
// Completion flows through the existing advance-mission function, which already
// dual-writes step.completed / mission.completed to bylda_events. This function
// only generates the structure and flips the casefile to 'approved'.

import { createClient } from "npm:@supabase/supabase-js@2.45.0";
import { callClaude } from "../_shared/helpers.ts";
import {
  buildLessons,
  classifyBusinessModel,
  STAGE_ORDER,
  type BusinessModel,
  type Stage,
} from "../_shared/curriculum.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

function json(body: unknown, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}

// Founder-facing module title per stage (curriculum language, not tool names).
// Used only for the template fallback; the AI names its own modules.
const STAGE_MODULE_LABELS: Record<Stage, string> = {
  Idea: "Clarify the idea",
  Validate: "Offer & proof",
  Launch: "First customers",
  Operate: "Run the machine",
  Scale: "Compound growth",
};

// Module intro line per stage, in plain language (template fallback).
const STAGE_MODULE_INTRO: Record<Stage, string> = {
  Idea: "Lock down what you're building and who it's for before anything else.",
  Validate: "Turn the idea into an offer people will actually pay for.",
  Launch: "Get your first real customers through the door.",
  Operate: "Build the systems that run the business without you.",
  Scale: "Compound what works into durable growth.",
};

// missions.lane is the workspace_lane enum (Idea | Offer | Customer | Systems).
const STAGE_LANE: Record<Stage, string> = {
  Idea: "Idea",
  Validate: "Offer",
  Launch: "Customer",
  Operate: "Systems",
  Scale: "Systems",
};

// One mentor owns each module, chosen by stage. Ids must match the `mentors`
// table seed (supabase/migrations/20260706000002_mentor_curriculum.sql).
const STAGE_MENTOR: Record<Stage, string> = {
  Idea: "dhruv-patel",
  Validate: "maya-okafor",
  Launch: "mo-latif",
  Operate: "priya-nair",
  Scale: "dhruv-patel",
};

// The real, clickable Launchpad tools (URL keys from src/lib/mock.ts).
// A step's tool_key is honored ONLY if it's in this set — otherwise the step is
// a plain manual action (no "Start this step" deep-link), which keeps the course
// UI from ever routing to a 404.
const VALID_TOOL_KEYS = new Set<string>([
  "ad-copy",
  "ad-creative",
  "automation",
  "blog",
  "business-plan",
  "business-plan-generator",
  "client-report",
  "cold-email",
  "competitor",
  "competitor-scanner",
  "email-sequence",
  "first-10-customers",
  "first-10-customers-finder",
  "followup",
  "funding-readiness-score",
  "funding-score",
  "gtm-strategy",
  "gtm-strategy-builder",
  "icp",
  "idea-validator",
  "idea-vs-idea",
  "investor-email-writer",
  "investor-emails",
  "invoice",
  "kill-my-idea",
  "kpi-dashboard",
  "landing-page",
  "landing-page-creator",
  "launch-checklist",
  "lead-capture",
  "lead-magnet",
  "mvp-planner",
  "niche-scorer",
  "niche-validator",
  "offer",
  "onboarding",
  "ops-plan",
  "persona-builder",
  "pitch-deck",
  "pitch-generator",
  "positioning-engine",
  "pricing",
  "pricing-calculator",
  "reporting",
  "reputation",
  "revenue-projector",
  "sales-script",
  "seo-audit",
  "social",
  "vsl",
  "website-audit",
]);

// Normalized shape both the AI path and the template fallback produce, so the
// database insertion loop is written once.
interface NormalizedStep {
  title: string;
  instruction: string;
  tool_key: string | null;
  target_ui_ref: string | null;
  action_type: string | null;
}
interface NormalizedModule {
  stage: Stage;
  title: string;
  intro: string;
  mentorOwner: string;
  steps: NormalizedStep[];
}

interface CasefileRun {
  id: string;
  organization_id: string;
  tool_key: string;
  input: Record<string, unknown> | null;
  casefile_status: string | null;
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });
  if (req.method !== "POST") return json({ error: "Method not allowed" }, 405);

  const authHeader = req.headers.get("Authorization");
  if (!authHeader) return json({ error: "Missing Authorization header" }, 401);

  const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
  const anonKey = Deno.env.get("SUPABASE_ANON_KEY")!;
  const userClient = createClient(supabaseUrl, anonKey, {
    global: { headers: { Authorization: authHeader } },
  });
  const { data: userData, error: userErr } = await userClient.auth.getUser();
  if (userErr || !userData?.user) return json({ error: "Invalid token" }, 401);
  const userId = userData.user.id;

  const serviceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
  const admin = createClient(supabaseUrl, serviceKey);

  let body: { casefile_run_id?: string };
  try {
    body = await req.json();
  } catch {
    return json({ error: "Invalid JSON" }, 400);
  }
  if (!body.casefile_run_id) return json({ error: "casefile_run_id is required" }, 400);

  // ── Load the casefile, scoped to a workspace the caller owns ───────────────
  const { data: run } = await admin
    .from("tool_runs")
    .select("id, organization_id, tool_key, input, casefile_status")
    .eq("id", body.casefile_run_id)
    .maybeSingle();
  if (!run) return json({ error: "Casefile not found" }, 404);
  const casefile = run as CasefileRun;

  const { data: ws } = await admin
    .from("workspaces")
    .select("id, organization_id, owner_id, stage")
    .eq("owner_id", userId)
    .maybeSingle();
  if (!ws) return json({ error: "No workspace for user" }, 404);
  if (ws.organization_id !== casefile.organization_id)
    return json({ error: "Casefile does not belong to your workspace" }, 403);

  // ── Idempotency — a course already exists for this workspace ───────────────
  const { data: existing } = await admin
    .from("missions")
    .select("id")
    .eq("workspace_id", ws.id)
    .not("generated_from_casefile_id", "is", null)
    .limit(1);
  if (existing && existing.length > 0) {
    // Still make sure the casefile shows approved, then no-op.
    await admin
      .from("tool_runs")
      .update({ casefile_status: "approved", casefile_approved_at: new Date().toISOString() })
      .eq("id", casefile.id);
    return json({ ok: true, already_generated: true });
  }

  // ── Resolve stage + business model + the business summary the AI reads ──────
  const stage: Stage = STAGE_ORDER.includes(ws.stage as Stage) ? (ws.stage as Stage) : "Idea";

  const { data: ctx } = await admin
    .from("business_context")
    .select("identity, customer, model, goals")
    .eq("organization_id", casefile.organization_id)
    .maybeSingle();
  // business_context stores jsonb blobs; flatten the relevant ones plus the
  // casefile's own input into one bag the classifier + AI can read from.
  const bag: Record<string, unknown> = {
    ...asObj(ctx?.model),
    ...asObj(ctx?.identity),
    ...asObj(ctx?.customer),
    ...asObj(ctx?.goals),
    ...(casefile.input ?? {}),
  };
  const signals = {
    monetization: str(bag.monetization),
    industry: str(bag.industry),
    idea: str(bag.idea ?? bag.description ?? bag.business_description),
    niche: str(bag.niche ?? bag.target_customer),
  };
  const model: BusinessModel = classifyBusinessModel(signals);

  // ── Build the course: AI-first, template fallback ──────────────────────────
  let modulesData: NormalizedModule[] = [];
  let generatedBy: "ai" | "template" = "ai";
  try {
    modulesData = await generateCourseWithAI(bag, signals, model, stage);
  } catch (_e) {
    modulesData = [];
  }
  if (modulesData.length === 0) {
    modulesData = buildFromTemplates(model, stage);
    generatedBy = "template";
  }
  if (modulesData.length === 0) return json({ error: "Could not build a course" }, 500);

  // ── Pause any pre-existing ad-hoc (non-course) active missions so the course
  //    becomes the single source of "what's next". Reversible status change. ──
  await admin
    .from("missions")
    .update({ status: "paused" })
    .eq("workspace_id", ws.id)
    .eq("status", "active")
    .is("generated_from_casefile_id", null);

  // ── Insert modules (missions) + steps (mission_steps) ──────────────────────
  let firstModuleId: string | null = null;
  const nowIso = new Date().toISOString();

  for (let m = 0; m < modulesData.length; m++) {
    const mod = modulesData[m];
    const moduleStatus = m === 0 ? "active" : "locked";

    const { data: mission, error: mErr } = await admin
      .from("missions")
      .insert({
        workspace_id: ws.id,
        title: mod.title,
        description: mod.intro,
        lane: STAGE_LANE[mod.stage],
        status: moduleStatus,
        sort_order: m,
        mentor_owner: mod.mentorOwner,
        generated_from_casefile_id: casefile.id,
        unlock_condition: m === 0 ? null : `complete_module:${m - 1}`,
      })
      .select("id")
      .single();
    if (mErr || !mission) return json({ error: mErr?.message ?? "Module insert failed" }, 500);
    if (m === 0) firstModuleId = mission.id;

    const steps = mod.steps.map((s, i) => ({
      mission_id: mission.id,
      title: s.title,
      description: s.instruction,
      instruction: s.instruction,
      tool_key: s.tool_key,
      target_ui_ref: s.target_ui_ref,
      action_type: s.action_type,
      completion_event: "step.completed",
      status: "pending",
      sort_order: i,
    }));
    const { error: sErr } = await admin.from("mission_steps").insert(steps);
    if (sErr) return json({ error: sErr.message }, 500);
  }

  // ── Point the workspace at the first module + flip casefile approved ───────
  if (firstModuleId) {
    await admin.from("workspaces").update({ current_mission_id: firstModuleId }).eq("id", ws.id);
  }
  await admin
    .from("tool_runs")
    .update({ casefile_status: "approved", casefile_approved_at: nowIso })
    .eq("id", casefile.id);

  // Announce the course build on the event ledger (same best-effort pattern as
  // advance-mission's bylda_events dual-writes).
  await admin
    .from("bylda_events")
    .insert({
      organization_id: casefile.organization_id,
      source: "course",
      event_type: "course.generated",
      subject_type: "workspace",
      subject_id: ws.id,
      payload: {
        casefile_run_id: casefile.id,
        modules: modulesData.length,
        stage,
        model,
        generated_by: generatedBy,
      },
    })
    .then(
      () => {},
      () => {},
    );

  return json({
    ok: true,
    modules: modulesData.length,
    first_module_id: firstModuleId,
    generated_by: generatedBy,
  });
});

// ── AI course generation ─────────────────────────────────────────────────────
// Reads the real business and returns an ordered, stage-by-stage program of
// concrete steps. Throws on any failure so the caller falls back to templates.

async function generateCourseWithAI(
  bag: Record<string, unknown>,
  signals: { monetization?: string | null; industry?: string | null; idea?: string | null; niche?: string | null },
  model: BusinessModel,
  stage: Stage,
): Promise<NormalizedModule[]> {
  const summary = businessSummary(bag, signals, model, stage);

  const system = `You are Bylda's course builder. A founder just approved their business plan, and you turn it into a personalized, do-this-now launch course — the way a great operator would walk a friend through starting THIS exact business, one concrete action at a time.

RULES
- Write for a total beginner at a 5th-grade reading level. Short sentences.
- Every step is ONE concrete action the founder can do today. Name the real thing to do: e.g. for an online store — "Buy a domain name", "Open your online store", "Connect your domain to your store", "Find your first product to sell". Never vague ("think about branding") — always specific ("Pick one product to sell and write its title, price, and 3 bullet points").
- When a step needs an outside service, name a common one in the "resource" field (e.g. "Namecheap or GoDaddy", "Shopify", "Stripe", "AliExpress or a local supplier"). Do NOT invent brands.
- Some steps are done INSIDE Bylda. When one clearly maps to a Bylda tool, set "tool_key" to EXACTLY one of the allowed keys below. Otherwise leave tool_key empty and use "resource".
- Order everything so each step only needs things from earlier steps. Real sequence, no jumping ahead.
- Group steps into 4-6 modules, each tied to a stage: Idea, Validate, Launch, Operate, Scale (in that order; skip a stage only if it truly doesn't apply). 3-6 steps per module.
- Tailor to the business. An e-commerce store, a consulting practice, and a SaaS app should get genuinely different courses.

ALLOWED tool_key VALUES (use only these, or leave empty):
${Array.from(VALID_TOOL_KEYS).join(", ")}`;

  const user = `Build the course for this founder.

${summary}

Return 4-6 modules, each a stage with a short plain-language title and intro, and its ordered concrete steps.`;

  const schema = {
    name: "founder_course",
    description:
      "A concrete, sequential, personalized launch course for this specific founder's business.",
    parameters: {
      type: "object",
      properties: {
        modules: {
          type: "array",
          description: "Ordered modules, one per stage, earliest stage first.",
          items: {
            type: "object",
            properties: {
              stage: {
                type: "string",
                enum: ["Idea", "Validate", "Launch", "Operate", "Scale"],
              },
              title: { type: "string", description: "Plain-language module title the founder sees." },
              intro: { type: "string", description: "One sentence on what this module gets done." },
              steps: {
                type: "array",
                items: {
                  type: "object",
                  properties: {
                    title: { type: "string", description: "Short action title, e.g. 'Buy your domain name'." },
                    instruction: {
                      type: "string",
                      description: "1-3 plain sentences telling the founder exactly what to do.",
                    },
                    tool_key: {
                      type: "string",
                      description:
                        "One of the allowed Bylda tool keys if this step is done inside Bylda; otherwise empty string.",
                    },
                    resource: {
                      type: "string",
                      description:
                        "Outside service/site to use if this is a manual step (e.g. 'Shopify'); otherwise empty string.",
                    },
                  },
                  required: ["title", "instruction"],
                },
              },
            },
            required: ["stage", "title", "steps"],
          },
        },
      },
      required: ["modules"],
    },
  };

  const result = await callClaude(system, user, schema);
  return normalizeAIModules(result);
}

function businessSummary(
  bag: Record<string, unknown>,
  signals: { monetization?: string | null; industry?: string | null; idea?: string | null; niche?: string | null },
  model: BusinessModel,
  stage: Stage,
): string {
  const lines: string[] = [];
  const name = str(bag.name ?? bag.business_name);
  if (name) lines.push(`Business name: ${name}`);
  if (signals.idea) lines.push(`What they're building: ${signals.idea}`);
  if (signals.industry) lines.push(`Industry/niche: ${signals.industry}`);
  const target = str(bag.target ?? bag.target_customer ?? bag.customer);
  if (target || signals.niche) lines.push(`Target customer: ${target ?? signals.niche}`);
  if (signals.monetization) lines.push(`How they make money: ${signals.monetization}`);
  const goal = str(bag.goal ?? bag.primary_goal ?? bag.objective);
  if (goal) lines.push(`Main goal: ${goal}`);
  lines.push(`Detected business type: ${model}`);
  lines.push(`Current stage: ${stage}`);
  // Include the raw bag so nothing useful is lost, but keep it bounded.
  const raw = JSON.stringify(bag).slice(0, 2500);
  lines.push(`\nRaw onboarding/context data:\n${raw}`);
  return lines.join("\n");
}

function normalizeAIModules(result: Record<string, unknown>): NormalizedModule[] {
  const rawModules = Array.isArray((result as { modules?: unknown }).modules)
    ? ((result as { modules: unknown[] }).modules as Record<string, unknown>[])
    : [];

  const byStage = new Map<Stage, NormalizedModule>();
  const out: NormalizedModule[] = [];

  for (const rm of rawModules) {
    const stage = rm.stage as Stage;
    if (!STAGE_ORDER.includes(stage)) continue;
    const title = str(rm.title) ?? STAGE_MODULE_LABELS[stage];
    const intro = str(rm.intro) ?? STAGE_MODULE_INTRO[stage];
    const rawSteps = Array.isArray(rm.steps) ? (rm.steps as Record<string, unknown>[]) : [];

    const steps: NormalizedStep[] = [];
    for (const rs of rawSteps) {
      const stitle = str(rs.title);
      let instruction = str(rs.instruction);
      if (!stitle || !instruction) continue;

      const rawKey = str(rs.tool_key);
      const toolKey = rawKey && VALID_TOOL_KEYS.has(rawKey) ? rawKey : null;
      const resource = str(rs.resource);
      // Fold the outside resource into the instruction for manual steps so the
      // founder can see exactly where to go (the course UI renders instruction
      // text; manual steps show no deep-link button).
      if (!toolKey && resource && !instruction.toLowerCase().includes(resource.toLowerCase())) {
        instruction = `${instruction} (Where: ${resource})`;
      }

      steps.push({
        title: stitle,
        instruction,
        tool_key: toolKey,
        target_ui_ref: toolKey ? `/app/launchpad/${toolKey}` : null,
        action_type: toolKey ? "navigate" : null,
      });
    }
    if (steps.length === 0) continue;

    // Merge duplicate stages into one module rather than dropping either.
    const existing = byStage.get(stage);
    if (existing) {
      existing.steps.push(...steps);
    } else {
      const mod: NormalizedModule = {
        stage,
        title,
        intro,
        mentorOwner: STAGE_MENTOR[stage],
        steps,
      };
      byStage.set(stage, mod);
      out.push(mod);
    }
  }

  // Order modules by the canonical stage order.
  out.sort((a, b) => STAGE_ORDER.indexOf(a.stage) - STAGE_ORDER.indexOf(b.stage));
  return out;
}

// ── Template fallback ─────────────────────────────────────────────────────────
// The pre-AI behavior: stitch the shared curriculum templates into modules by
// stage. Only runs when the AI call fails, so a founder always gets a course.

function buildFromTemplates(model: BusinessModel, stage: Stage): NormalizedModule[] {
  const lessons = buildLessons(model, stage);
  const byStage = new Map<Stage, NormalizedModule>();
  const out: NormalizedModule[] = [];

  for (const l of lessons) {
    const toolKey = VALID_TOOL_KEYS.has(l.toolKey) ? l.toolKey : null;
    const step: NormalizedStep = {
      title: l.title,
      instruction: l.summary,
      tool_key: toolKey,
      target_ui_ref: toolKey ? `/app/launchpad/${toolKey}` : null,
      action_type: toolKey ? "navigate" : null,
    };
    const existing = byStage.get(l.stage);
    if (existing) {
      existing.steps.push(step);
    } else {
      const mod: NormalizedModule = {
        stage: l.stage,
        title: STAGE_MODULE_LABELS[l.stage],
        intro: STAGE_MODULE_INTRO[l.stage],
        mentorOwner: STAGE_MENTOR[l.stage],
        steps: [step],
      };
      byStage.set(l.stage, mod);
      out.push(mod);
    }
  }

  out.sort((a, b) => STAGE_ORDER.indexOf(a.stage) - STAGE_ORDER.indexOf(b.stage));
  return out;
}

function str(v: unknown): string | null {
  return typeof v === "string" && v.trim() ? v.trim() : null;
}

function asObj(v: unknown): Record<string, unknown> {
  return v && typeof v === "object" ? (v as Record<string, unknown>) : {};
}
